### ISSUE TITLE
Error: "Can't find pane: mouse"

### ISSUE THREAD

**Issue by aexkcz** [noscript/tmux-mighty-scroll#1]
I installed via tpm and when I'm trying to scroll in manpages i get this message in the tmux status bar.
i used the example configuration:
```
set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @mighty-scroll-interval 3
set -g @mighty-scroll-by-line 'man fzf'
set -g @mighty-scroll-select-pane off

   
  run '~/.tmux/plugins/tpm/tpm'
```
does it still work? tmux version is 3.0a

**Comment by aexkcz** [comment]
seems I'm not the only one
https://unix.stackexchange.com/questions/703366/tmux-doesnt-uninstall-plugin

**Comment by noscript** [comment]
Apparently in 3.0a long tokens like `{mouse}` have to be quoted. Please try 23e9ab1.

**Comment by aexkcz** [comment]
Thanks! seems fixed
