### ISSUE TITLE
No effect with tmux3.2 and iTerm2 

### ISSUE THREAD

**Issue by victorkristof** [noscript/tmux-mighty-scroll#2]
Hi there,

Your plugin looks super nice but I cannot get it to work with tmux3.2 in iTerm2.
It basically has no effect.

I added this to my tmux.conf:

```tmux
set-option -g @plugin 'noscript/tmux-mighty-scroll'
set-option -g mouse on
set-option -g @mighty-scroll-by-line 'man fzf less vim mvim'
```

Scrolling from within `vim` scrolls `tmux` instead.

Any idea how to fix it?

**Comment by noscript** [comment]
Hi. I don't have mac at hand but I think there is no `/proc` filesystem on macOS, so `pscheck` doesn't work. I'll try to see if adding macOS support is a lot of work.

**Comment by victorkristof** [comment]
Sounds great, thanks!

**Comment by noscript** [comment]
959a8c595c36204b751bb3bb1b96d4701c7d3718 adds macOS support.

Since there is no native API to list process children on macOS and I don't want to parse `ps` output, there is only a Shell implementation of the process checker.
